name: ct312hm01_temp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12 #hiển thị thông báo sau đó tự động tắt, khác với ShowDialog là user phải tắt
  flutter_markdown: ^0.6.17
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.18.0
  lottie:
  animated_splash_screen:
  flutter_launcher_icons: ^0.14.3
  flutter_tts: ^4.2.2 #tts
  speech_to_text: ^7.0.0 #stt





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #using this instead of .env for website compatibility
    - lib/dotenv
    - assets/avatar/logo.png
    - assets/chat_app.db
    - assets/image/background.png
    - assets/image/background2.png
    - assets/animation_splash_screen.json
    - assets/icon/ic_launcher.png
    - assets/icon/ic_launcher_foreground.png
    - assets/icon/ic_launcher_round.png

